name: Docker CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u PiMachineLearning --password-stdin
          
      - name: Prepare images
        run: |
            cd $GITHUB_WORKSPACE
            sudo apt-get install -y qemu-user-static binfmt-support
            chmod +x main.sh all.sh
            ./all.sh
